source 'https://rubygems.org'

gem 'aws-sdk',    '1.66.0'
gem 'httpclient', '=2.7.1'
gem 'bosh_common', '=0000'
gem 'bosh_cpi', '=0000'

group :development, :test do
  gem 'rspec', '~> 3.0.0'
  gem 'rake', '~>10.3.2'
  gem 'webmock'
end
