---
final_name: bosh-aws-cpi
blobstore:
  provider: s3
  options:
    bucket_name: spotinst-public/integrations/bosh/aws/cpi-blobs
    signature_version: "2" # see: https://github.com/cloudfoundry/bosh-cli/issues/292#issuecomment-321799720